services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - laravel
    depends_on:
      - db
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=toeic_db
      - DB_USERNAME=laravel
      - DB_PASSWORD=laravel
      - upload_max_filesize=100M
      - post_max_size=100M
      - max_execution_time=300
      - memory_limit=256M

  nginx:
    image: nginx:latest
    container_name: laravel_nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel
    environment:
      - client_max_body_size=100M

  db:
    image: mysql:8.0
    container_name: laravel_db
    restart: always
    environment:
      MYSQL_DATABASE: toeic_db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    ports:
      - "3307:3306"
    networks:
      - laravel
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/sql/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql

networks:
  laravel:

volumes:
  mysql_data: